#!/bin/bash

BASE_COLLECTION_PATH="/must-gather"
mkdir -p ${BASE_COLLECTION_PATH}

ANSIBLECRD="automationcontrollerbackups.automationcontroller.ansible.com \
  automationcontrollerrestores.automationcontroller.ansible.com \
  automationcontrollers.automationcontroller.ansible.com \
  automationhubbackups.automationhub.ansible.com \
  automationhubrestores.automationhub.ansible.com \
  automationhubs.automationhub.ansible.com \
  edas.eda.ansible.com \
  edabackups.eda.ansible.com \
  edarestores.eda.ansible.com \
  ansiblecredentials.tower.ansible.com \
  ansibleinstancegroups.tower.ansible.com \
  ansibleinventories.tower.ansible.com \
  ansibleprojects.tower.ansible.com \
  ansibleschedules.tower.ansible.com \
  ansiblejobs.tower.ansible.com \
  ansibleworkflows.tower.ansible.com \
  jobtemplates.tower.ansible.com \
  workflowtemplates.tower.ansible.com \
  ansibleaiconnects.aiconnect.ansible.com"

oc adm inspect customresourcedefinition.apiextensions.k8s.io $ANSIBLECRD --dest-dir=must-gather

for i in $ANSIBLECRD; do
  oc adm inspect $i -n $1 --dest-dir=must-gather
done

oc adm inspect ns/"$1"  --dest-dir=must-gather
oc get pods -n $1 >> ${BASE_COLLECTION_PATH}/gather-aap.log
